IT_code_hw9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls'))
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.IndexTemplate.as_view(), name='index'),
    path('about_site', views.AboutList.as_view()),
    path('about_author/<int:pk>', views.AuthorDetail.as_view()),
    path('book/<int:pk>', views.BookDetail.as_view(), name='book'),
    path('add_book/', views.BookAdd.as_view(), name='add_book'),
    path('update_book/<int:pk>', views.BookUpdate.as_view(), name='update_book'),
    path('delete_book/<int:pk>', views.BookDelete.as_view(), name='delete_book'),

]

books/models.py
from django.db import models

# Create your models here.
CENSOR_CHOICE = (
    ('C', 'Для детей'), # c child
    ('G', 'Для взрослых'), # g grow-up
    ('A', 'Для всех'), # a all
)

class BookGenre(models.Model):
    genre_book = models.CharField(
        max_length=255,
        help_text='Введите жанр произведения',
        verbose_name='Жанр произведения',
    )

    def __str__(self):
        return self.genre_book

class BookAuthor(models.Model):
    firstName_author = models.CharField(
        max_length=255,
        help_text='Введите имя автора(Обязательно)',
        verbose_name='Имя автора',
        null=True,
    )
    lastName_author = models.CharField(
        max_length=255,
        help_text='Введите фамилию автора(Обязательно)',
        verbose_name='Фамилия автора',
        null=True,
    )

    def __str__(self):
        return self.get_fullname()
    
    def get_fullname(self) -> str:
        return ' '.join(filter(bool, [self.firstName_author, self.lastName_author]))

class Book(models.Model):
    title_book = models.CharField(
        max_length=255,
        help_text='Введите название произведения(Обязательно)',
        unique=True,
        verbose_name='Название',
    )
    
    censor = models.CharField(
        max_length=255,
        help_text='Введите тип произведения',
        verbose_name='Цензура',  
        choices=CENSOR_CHOICE,
        default=CENSOR_CHOICE[1],
    )
    
    genre_book = models.ManyToManyField(BookGenre, verbose_name='Жанр произведения')
    
    author = models.ForeignKey(BookAuthor, on_delete=models.CASCADE, verbose_name='Имя и фамилия автора')
    
    content_book = models.TextField(
        help_text='Введите текст произведения(Обязательно)',
        verbose_name='Текст',
    )
    
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата добавления',
        null=True
    )
    
    time_update = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата изменения',
    )

books/forms.py
from django import forms
import re
from books import models
import string

# class BooksSearch(forms.Form):
#     title_book = forms.CharField(label='Поиск по названию книги', 
#                                 required=False,
#                                 widget=forms.TextInput(attrs={'placeholder': 'Поиск по названию книги'})
#                                 )
    
#     author = forms.CharField(label='Поиск по автору книги', 
#                             required=False,
#                             widget=forms.TextInput(attrs={'placeholder': 'Поиск по автору книги'}) 
#                             )
    
#     # def clean_title_book(self):
#     #     title = self.cleaned_data["title_book"]
#     #     if '/' in title:
#     #         raise forms.ValidationError("Имя не должно содержать '/' !")
#     #     return title
    
#     def clean(self):
#         title = self.cleaned_data.get("title_book")
#         author = self.cleaned_data.get("author")

#         if title and re.search(r"[^/a-zA-Z0-9а-яА-Я\s]", title):
#             raise forms.ValidationError(
#                 "Название книги содержит недопустимые символы, кроме '/'!")

#         if author and re.search(r"[^/a-zA-Z0-9а-яА-Я\s]", author):
#             raise forms.ValidationError(
#                 "Имя автора содержит недопустимые символы!")

#         return title

class BookForm(forms.ModelForm):
    title_book = forms.CharField(label='Название произведения')
    genre_book = forms.ModelMultipleChoiceField(
        label='Жанр произведения',
        queryset=models.BookGenre.objects.all(),
        required=False,
        widget=forms.SelectMultiple,
    )
    class Meta:
        model = models.Book
        fields = '__all__'
        # fields = ('title_book', 'genre', 'content_book')

    # Проверка в названии книги на недопустимые знаки
    def clean_title_book(self):
        title_book = self.cleaned_data['title_book']
        allowed_punctuation = [',', '.', '!', '?', ':', '-', "'", '"']

        for char in title_book:
            if char in string.punctuation and char not in allowed_punctuation:
                raise forms.ValidationError("Название произведения содержит недопустимые символы пунктуации.")

        return title_book

books/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from books import models, forms
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.urls import reverse_lazy
from books import filters
# Create your views here.

class TitleMixin():
    title = None

    def get_title(self):
        return self.title
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context

class BookDetail(TitleMixin, DetailView):
    model = models.Book
    template_name = 'books/book.html'
    context_object_name = 'book'
    title = "Содержание книги"

class IndexTemplate(TitleMixin, ListView):
    template_name = 'books/index.html'
    title = "Главная страница"
    model = models.Book
    context_object_name = 'books'

    def get_filters(self):
        return filters.BooksFilter(self.request.GET)
    
    def get_queryset(self):
        # title_book = self.request.GET.get("title_book")
        # author = self.request.GET.get("author")
        # qs = models.Book.objects.all()
        # if title_book or author:
        #     return qs.filter(
        #             Q(title_book__iregex=title_book) &
        #             (Q(author__firstName_author__iregex=author) |
        #             Q(author__lastName_author__iregex=author))
        #                 )
        return self.get_filters().qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = forms.BooksSearch(self.request.GET or None)
        context['filter'] = self.get_filters()
        return context

class AuthorDetail(TitleMixin, DetailView):
    model = models.BookAuthor
    template_name = 'books/about_author.html'
    context_object_name = 'author'
    title = 'Информация об авторе' 

class AboutList(TitleMixin, ListView):
    template_name = 'books/about_site.html'
    title = 'О вебсайте'
    model = models.Book

class BookAdd(TitleMixin, CreateView):
    form_class = forms.BookForm

    template_name = 'books/add_book.html'
    title = 'Добавление книги'
    model = models.Book
    success_url = reverse_lazy('books:index')

class BookUpdate(TitleMixin, UpdateView):
    form_class = forms.BookForm

    template_name = 'books/update_book.html'
    title = 'Изменение книги'
    model = models.Book
    success_url = reverse_lazy('books:index')

class BookDelete(TitleMixin, DeleteView):
    model = models.Book
    template_name = 'books/delete_book.html'
    title = 'Удаление книги'
    success_url = reverse_lazy('books:index')

books/templates/books/about_author.html
{% extends 'books/template_site.html'%}



{% block content %}

<h1>Автор</h1>
<p>Краткие сведения об авторе</p>

<h1>{{author.firstName_author}} {{author.lastName_author}}</h1>


{% endblock %}

books/templates/books/about_site.html
{% extends 'books/template_site.html'%}


{% block content %}

<h1>О проекте...</h1>
<p class="content_book">
	Добро пожаловать на наш веб-сайт, посвященный удивительному миру книг!
	Здесь вы найдете обширный список книг на самые разнообразные темы, которые
	погрузят вас в мир воображения, знаний и приключений.
	Мы собрали для вас огромную коллекцию книг, включающую классические
	произведения, бестселлеры, научно-популярную литературу, фантастику,
	детективы, романы, и многое другое. Независимо от ваших предпочтений, вы
	обязательно найдете что-то по душе.
</p>


{% endblock %}

books/templates/books/add_book.html
{% extends 'books/template_site.html'%}



{% block content %}

<h1>Книга</h1>
<p>Добавление книги на сайт</p>

<form action="{% url 'books:add_book' %}" method="POST">
	{% csrf_token%}
	{{form.as_div}}
	<button class="btn btn-primary" type="submit">Добавить книгу</button>
</form>



{% endblock %}

books/templates/books/book.html
{% extends 'books/template_site.html'%}



{% block content %}

<h1>{{book.title_book}}</h1>

<h3>Автор: {{book.author}}</h3>
<div>
	<p class="content_book">{{book.content_book}}</p>
</div>



{% endblock %}

books/templates/books/delete_book.html
{% extends 'books/template_site.html'%}



{% block content %}

<h1>Книга</h1>
<p>Удаление книги "{{book.title_book}}" автора "{{book.author}}" с сайта</p>

<form action="{% url 'books:delete_book' pk=book.pk %}" method="POST">
	{% csrf_token%}
	{{form}}
	<button class="btn btn-primary" type="submit">Удалить книгу</button>
	<button class="btn btn-primary" type="reset">Отменить</button>
</form>



{% endblock %}

books/templates/books/index.html
{% extends 'books/template_site.html'%}


{% block content %}
<form method="GET">
	<div class="search_form">
		{{ filter.form.title_book }}
	</div>
	<div class="search_form">
		{{ filter.form.author }}
	</div>
	<button class="btn btn-primary" style="width: 300px; margin-left: 5px;">Поиск</button>
</form>

<h1>Список книг</h1>

<ol>
	{% for book in books %}
	<li>
		<div class="list_books_and_authors">
			<a href="book/{{book.pk}}">
				<h4>{{book.title_book}} |&#160;</h4>
			</a>
			<a href="about_author/{{book.author.pk}}">
				<h4>{{book.author}} &#160;</h4>
			</a>
			{% if request.user.is_superuser %}
				<a class="fix_book" href="update_book/{{book.pk}}">
					<p>Изменить \&#160;</p>
				</a>
				<a class="fix_book" href="{% url 'books:delete_book' pk=book.pk%}">
					<p>Удалить</p>
				</a>
			{% endif %}
			<!-- <p><h4>{{book.genre_book}}</h4></p> -->
		</div>
	</li>
	{% empty %}
	<a href="">
		<h4>Книги не найдены</h4>
	</a>
	{% endfor %}
</ol>

<footer>
	<a href="about_site">О нас</a>
</footer>


{% endblock %}

books/templates/books/template_site.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<title>{% block title %} {{ title }} {% endblock %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'books/css/style.css' %}">
</head>

<body>
	<!-- nav_menu -->
	<nav class="nav_menu">
		<div>
			<ul class="content_nav_menu">
				<li>
					<a class="nav-link" href="{% url 'books:index' %}">Главная страница</a>
				</li>
				<li>
					<a class="nav-link" href="{% url 'books:add_book' %}">Добавить книгу</a>
				</li>
				<li>
					<a class="nav-link" href="/admin/">Администрирование</a>
				</li>
			</ul>
		</div>
	</nav>

	{% block content %}

	{% endblock %}
</body>

</html>

books/templates/books/update_book.html
{% extends 'books/template_site.html'%}



{% block content %}

<h1>Книга</h1>
<p>Изменение книги на сайте</p>

<form action="{% url 'books:update_book' pk=book.pk %}" method="POST">
	{% csrf_token%}
	{{ form.as_div}}
	<button class="btn btn-primary" type="submit">Изменить книгу</button>
	<button class="btn btn-primary" type="reset">Отменить</button>
</form>



{% endblock %}